### ISSUE TITLE
Clarification in performance section about formation of transactions for testing

### ISSUE THREAD

**Issue by gwtaylor** [ebuchman/thesis#24]
https://github.com/ebuchman/thesis/blob/cf2c124294208fab86018237887678c4c456d132/chapters/performance.tex#L25

"Transactions are 250 bytes in size (a reasonable size for including a few 32 or 64 byte hashes and signatures), where the leading bytes are Big-Endian encoded integers representing transaction number and validator index for that instance, the trailing 16 bytes are randomly drawn from the operating system, and the intermediate bytes are just zeroes."

I don't understand why the trailing bytes are random and the intermediate bytes are zeros. Is it to give some minimal amount of stochasticity?

**Comment by ebuchman** [comment]
yup, but to not waste too much time pulling the randomness
